### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by cathylacus** [eduble/gl#1]
Thank for your example,I find this error.
Traceback (most recent call last):
  File "./main.py", line 26, in <module>
    main()
  File "./main.py", line 18, in main
    if not ctx.initialize(WIDTH, HEIGHT):
  File "/test/liwei/PIFu-master/gl-master/libegl/context.py", line 10, in initialize
    if not self.initialize_on_device(device, width, height):
  File "/test/liwei/PIFu-master/gl-master/libegl/context.py", line 15, in initialize_on_device
    print("selected: " + device.name)
  File "/test/liwei/PIFu-master/gl-master/libegl/devices/generic.py", line 55, in name
    return "EGL device " + devstr.decode('ASCII')
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by cathylacus** [comment]
Ubuntu 16.04 and I just have Command interface without graphical interfaces,it's a server in our school.

**Comment by eduble** [comment]
Hello,
You can try to add a test after this line: 
https://github.com/eduble/gl/blob/94485a1c9f3eb4f62e5a21a018c814b4232b6b0a/libegl/devices/generic.py#L51
Something like that:
```
    devstr = egl.eglQueryDeviceStringEXT(self.egl_dev, EGL_DRM_DEVICE_FILE_EXT) 
    if devstr is None:
        return "EGL device unknown"
```
